#!/usr/bin/env bash
# =============================================================================
# publish.sh — reliable PUBLISH for a SpineRadiology editor edit.
#
# The hidden /admin editor can ONLY edit the BODY of an EXISTING article
# (lists existing docs/<cat>/<slug>.md, edits text, commits the same path —
# no create/delete/rename). Publishing is a SURGICAL BODY-SPLICE:
#   1. clean-regen the edited article through the real pipeline to get its
#      fully-TREATED <article> body, its head__meta (fresh "Updated" git date +
#      read-time), and the rebuilt custom search index;
#   2. restore the APPROVED overlay over site/ (every page exactly as shipped);
#   3. splice ONLY that body + head__meta into the edited article's approved
#      page, and drop in the rebuilt search index;
#   4. a hard DIFF-GATE (cmp manifest) proves NOTHING but the edited article(s)
#      + search index changed — else ABORT before any deploy;
#   5. deploy, then re-freeze the overlay so future build.sh stays consistent.
#
# Why not "just regenerate everything": a full regen drifts ~180 approved pages
# (dates/chrome) + hits gen_search/get_body idempotency landmines. The splice
# takes body+meta+index from the regen and EVERYTHING ELSE from the approved
# page, so it is immune to date drift, anatomy-ordering, and the get_body abort.
# See kevin-ops L-235/L-236/L-237.
#
# Usage:
#   redesign/publish.sh                   # changed docs = merge commit (git diff HEAD^ HEAD)
#   redesign/publish.sh --files a.md ...   # explicit list (paths under docs/)
#   redesign/publish.sh --dry-run [...]    # everything EXCEPT deploy + overlay re-freeze
#
# Requires: python3 with the PINNED toolchain below; a full (non-shallow) clone;
# the doc edit COMMITTED; wrangler authenticated.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # repo root (this script lives in redesign/)
cd "$ROOT"
SITE="$ROOT/site"
OVERLAY="$ROOT/redesign/snapshots/redesign-overlay.tar.gz"
BODIES="$ROOT/redesign/bodies"
PYBIN="${PUBLISH_PY:-python3}"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# Pinned toolchain. The ~109 non-overlay assets (css/js/png) are regenerated by
# mkdocs every run and are NOT covered by the diff-gate, so a version bump could
# ship drifted assets silently. We abort on drift; bump these intentionally and
# re-verify the live site, then update them here.
PIN_MKDOCS="1.6.1"; PIN_MATERIAL="9.7.5"; PIN_PLUGIN="1.5.1"; PIN_PIL="11.1.0"; PIN_GLIGHTBOX="0.5.2"
PIN_WRANGLER="4.85"                       # major.minor; wrangler changes [assets] upload semantics across versions
export WRANGLER_SEND_METRICS=false
# Resolve wrangler: a PATH-installed global (CI pins it) else npx (local Mac). Avoids npx silently
# downloading a different "latest" wrangler and deploying with it.
if command -v wrangler >/dev/null 2>&1; then WRANGLER="wrangler"; else WRANGLER="npx wrangler"; fi

DRYRUN=0
if [ "${1:-}" = "--dry-run" ]; then DRYRUN=1; shift; fi

say(){ printf '\033[36m[publish]\033[0m %s\n' "$*"; }
die(){ printf '\033[31m[publish ABORT]\033[0m %s\n' "$*" >&2; exit "${2:-1}"; }

# -- 0. preflight -------------------------------------------------------------
"$PYBIN" -c "import mkdocs, mkdocs_git_revision_date_localized_plugin, PIL" 2>/dev/null \
  || die "python env missing mkdocs / git-revision-date-localized plugin / Pillow (set PUBLISH_PY)" 1
"$PYBIN" - "$PIN_MKDOCS" "$PIN_MATERIAL" "$PIN_PLUGIN" "$PIN_PIL" "$PIN_GLIGHTBOX" <<'PY' \
  || die "toolchain drift / missing plugin — built assets may differ from the approved site. Verify the live site, then update PIN_* in publish.sh." 1
import sys
from importlib.metadata import version
want = dict(zip(["mkdocs","mkdocs-material","mkdocs-git-revision-date-localized-plugin","Pillow","mkdocs-glightbox"], sys.argv[1:6]))
bad = [f"{d}: have {version(d)} want {w}" for d, w in want.items() if version(d) != w]
if bad:
    sys.stderr.write("  " + "\n  ".join(bad) + "\n"); sys.exit(1)
PY
$WRANGLER --version 2>/dev/null | grep -q "$PIN_WRANGLER" \
  || die "wrangler version != $PIN_WRANGLER ($($WRANGLER --version 2>/dev/null | tr -d '\n')) — pin drift; verify a deploy then update PIN_WRANGLER" 1
[ -f "$OVERLAY" ] || die "approved overlay tarball missing: $OVERLAY" 1
[ -f "$ROOT/.git/shallow" ] && die "shallow clone — git 'Updated' dates would be wrong; use a full clone" 1
git diff --quiet -- "$OVERLAY" 2>/dev/null \
  || die "overlay tarball has uncommitted changes — commit or 'git checkout' it first" 1

# -- 1. resolve changed docs --------------------------------------------------
CHANGED=()
if [ "${1:-}" = "--files" ]; then
  shift; CHANGED=("$@")
else
  while IFS= read -r line; do [ -n "$line" ] && CHANGED+=("$line"); done \
    < <(git diff --name-only HEAD^ HEAD -- 'docs/*/*.md' 2>/dev/null || true)
fi
if [ "${#CHANGED[@]}" -eq 0 ]; then
  say "no docs/<cat>/<slug>.md changes vs HEAD^ — nothing to publish."
  say "(if you expected an edit, it may be behind stacked commits — re-run with:"
  say "   redesign/publish.sh --files docs/<cat>/<slug>.md )"
  exit 0
fi

# -- 2. baseline: extract the approved overlay -------------------------------
mkdir -p "$TMP/approved"; tar xzf "$OVERLAY" -C "$TMP/approved"

# -- 3. classify: body edit of an EXISTING article; assert a real git date ----
SLUGS=()
for f in "${CHANGED[@]}"; do
  rel="${f#docs/}"; cat="${rel%%/*}"; slug="$(basename "${rel%.md}")"
  [ "$slug" = "index" ] && die "$f is a category index — not editable via markdown (sourced from Emily's template)" 2
  printf '%s' "$slug" | grep -qE '^[a-z0-9-]+$' || die "slug '$slug' is not [a-z0-9-]+ — rename before publishing" 2
  [ -f "$TMP/approved/$cat/$slug/index.html" ] \
    || die "$cat/$slug is NEW (absent from approved overlay). Surgical publish = body edits only; an add needs a full rebuild + re-baseline." 2
  [ -f "$f" ] || die "$f was deleted. Surgical publish = body edits only; a delete needs a full rebuild + re-baseline." 2
  # The "Updated" date = the file's last git-commit date. If blame is missing (grafted/treeless
  # clone, orphaned squash) the plugin would silently stamp today's BUILD date. Refuse instead.
  [ -n "$(git log -1 --format=%cI -- "$f" 2>/dev/null)" ] \
    || die "$f has no git commit date — would publish a wrong 'Updated' date; commit it on a full-history clone" 2
  SLUGS+=("$cat/$slug")
done
say "body edit(s) to publish:"; for cs in "${SLUGS[@]}"; do say "    $cs"; done

# -- 4. clean regen → treated body + head__meta + rebuilt search index --------
say "clean build + treat (mkdocs -> gen_categories -> gen_articles -> gen_search)…"
rm -rf "$SITE"
for cs in "${SLUGS[@]}"; do rm -f "$BODIES/$cs.html"; done
"$PYBIN" -m mkdocs build >/dev/null
cp "$ROOT/redesign/her-cat.html" "$SITE/anatomy/index.html"      # anatomy cat page (gen_categories omits it)
"$PYBIN" "$ROOT/redesign/gen_categories.py" >/dev/null
"$PYBIN" "$ROOT/redesign/gen_articles.py"  >/dev/null
cp "$ROOT/redesign/landing.html"       "$SITE/index.html"
[ -f "$ROOT/redesign/spine-regions.html" ] && cp "$ROOT/redesign/spine-regions.html" "$SITE/spine-regions.html"
"$PYBIN" "$ROOT/redesign/gen_search.py" >/dev/null

# Keep the rebuilt custom search index (reflects the edited body). Without this the edit's new
# terms aren't searchable and removed terms still hit. (gen_search writes site/search-index.json.)
[ -f "$SITE/search-index.json" ] && cp "$SITE/search-index.json" "$TMP/search-index.json"

mkdir -p "$TMP/bodies"
for cs in "${SLUGS[@]}"; do
  key="$(printf '%s' "$cs" | tr '/' '_')"
  "$PYBIN" - "$SITE/$cs/index.html" "$TMP/bodies/$key.body" "$TMP/bodies/$key.meta" <<'PY'
import re, sys
h = open(sys.argv[1], encoding="utf-8").read()
b = re.search(r'<article class="article-body"[^>]*>(.*?)</article>', h, re.S)
if not b: sys.exit("could not extract treated body from %s" % sys.argv[1])
open(sys.argv[2], "w", encoding="utf-8").write(b.group(1))
# head__meta carries the fresh "Updated" git date + read-time for THIS edit. Structural self-check
# (like gen_articles' entry-anchor guard) so a future template change can't silently truncate it.
m = re.search(r'<div class="head__meta">.*?</div>', h, re.S)
meta = m.group(0) if m else ""
if not (meta and meta.count("<div") == 1 and "Updated" in meta and "Section" in meta and "Read" in meta):
    sys.exit("head__meta malformed/changed in %s — refusing (date bump would be wrong)" % sys.argv[1])
open(sys.argv[3], "w", encoding="utf-8").write(meta)
PY
  [ -s "$TMP/bodies/$key.body" ] || die "treated body for $cs is empty — regen failed" 5
  [ -s "$TMP/bodies/$key.meta" ] || die "head__meta for $cs is empty — regen failed" 5
done

# -- 5. restore APPROVED pages, then splice body + meta + search index --------
say "restore approved overlay + splice edited body(ies) + date…"
bash "$ROOT/redesign/restore.sh" >/dev/null
[ -f "$TMP/search-index.json" ] && cp "$TMP/search-index.json" "$SITE/search-index.json"
for cs in "${SLUGS[@]}"; do
  key="$(printf '%s' "$cs" | tr '/' '_')"
  "$PYBIN" - "$SITE/$cs/index.html" "$TMP/bodies/$key.body" "$TMP/bodies/$key.meta" <<'PY'
import re, sys
p = sys.argv[1]
nb = open(sys.argv[2], encoding="utf-8").read()
nm = open(sys.argv[3], encoding="utf-8").read()
h = open(p, encoding="utf-8").read()
h, n = re.subn(r'(<article class="article-body"[^>]*>).*?(</article>)',
               lambda m: m.group(1) + nb + m.group(2), h, count=1, flags=re.S)
if n != 1: sys.exit("body splice failed (matched %d) in %s" % (n, p))
# Bump "Updated" date + read-time on the edited article (hard-fail; never silently skip).
h, nm_n = re.subn(r'<div class="head__meta">.*?</div>', lambda m: nm, h, count=1, flags=re.S)
if nm_n != 1: sys.exit("head__meta not found in approved %s — cannot bump date" % p)
open(p, "w", encoding="utf-8").write(h)
PY
done

# -- 6. DIFF-GATE: only the edited page(s) + search-index may differ ----------
say "diff-gate: verifying only the edited page(s) changed…"
EXP="$TMP/expected.txt"; : > "$EXP"
echo "search-index.json" >> "$EXP"          # rebuilt to reflect the edit (allowed; not required)
for cs in "${SLUGS[@]}"; do echo "$cs/index.html" >> "$EXP"; done
sort -o "$EXP" "$EXP"

CHANGEDSET="$TMP/changed.txt"; : > "$CHANGEDSET"
while IFS= read -r af; do
  rel="${af#"$TMP/approved/"}"
  sf="$SITE/$rel"
  [ -f "$sf" ] || { echo "MISSING:$rel" >> "$CHANGEDSET"; continue; }
  cmp -s "$af" "$sf" || echo "$rel" >> "$CHANGEDSET"
done < <(find "$TMP/approved" -type f)
sort -o "$CHANGEDSET" "$CHANGEDSET"

# Collateral check: anything changed that we didn't sanction = drift → ABORT.
UNEXPECTED="$(comm -23 "$CHANGEDSET" "$EXP" || true)"
[ -z "$UNEXPECTED" ] || { printf '%s\n' "$UNEXPECTED" >&2; die "unexpected page(s) changed vs approved — NOT deploying" 4; }

# Report any edited article whose page didn't change (splice already succeeded above, so an
# unchanged edited page = a true no-op: its treated content equals what's already live).
for cs in "${SLUGS[@]}"; do
  grep -qx "$cs/index.html" "$CHANGEDSET" || say "already current (no content change): $cs"
done
# Deploy if ANYTHING in the gated set changed — an edited page and/or the search index (the latter
# repairs the live empty-body-text index even on a body no-op). Truly-nothing-changed = clean exit.
if [ ! -s "$CHANGEDSET" ]; then
  say "nothing changed vs the live site — already current. Not deploying."; exit 0
fi
nchg="$(wc -l < "$CHANGEDSET" | tr -d ' ')"
say "diff-gate PASSED — $nchg gated file(s) changed (edited page(s) and/or search index), 0 collateral."

# -- 7. smoke check the full deploy dir ---------------------------------------
[ -s "$SITE/index.html" ] || die "landing site/index.html missing/empty" 5
[ -d "$SITE/assets" ]     || die "site/assets missing" 5
marked="$(grep -rl 'sr-search-btn' "$SITE" --include=index.html | wc -l | tr -d ' ')"
[ "$marked" -ge 230 ] || die "only $marked redesign pages present (<230) — site looks incomplete" 5
say "smoke check OK ($marked redesign pages, landing + assets present)."

if [ "$DRYRUN" -eq 1 ]; then say "--dry-run: skipping deploy + overlay re-freeze. site/ is staged & verified."; exit 0; fi

# -- 8. deploy ----------------------------------------------------------------
$WRANGLER whoami >/dev/null 2>&1 || die "wrangler not authenticated (set CLOUDFLARE_API_TOKEN, or run: npx wrangler login)" 6
say "deploying to production…"
$WRANGLER deploy

# -- 9. re-freeze the overlay so future build.sh keeps the edit ---------------
bash "$ROOT/redesign/snapshot.sh" \
  || die "LIVE IS UPDATED but overlay re-freeze FAILED — run 'bash redesign/snapshot.sh' then commit the overlay BEFORE the next publish (else restore.sh reverts this edit)" 7
# Signal CI (the Action) that a real deploy + re-freeze happened, so it commits the overlay back
# only on a true publish (not a no-op). Both deploy + snapshot are proven done if we reach here.
[ -n "${GITHUB_OUTPUT:-}" ] && echo "deployed=true" >> "$GITHUB_OUTPUT"
say "DONE. Live + overlay re-frozen."
say "COMMIT the refreshed overlay + bodies so the repo stays source of truth:"
say "    git add redesign/snapshots/redesign-overlay.tar.gz redesign/bodies && git commit -m 'publish: <article>' && git push origin main"
